version: 0.2
env:
variables:
        S3_BUCKET: "www.enriquemartinezmedia.com",
        ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --${ENV} 
    post_build:
         commands:
            # Emptying the s3 bucket
            - aws s3 rm s3://${S3_BUCKET} --recursive - echo S3 bucket is cleared.
            - aws s3 cp dist s3://${S3_BUCKET} --recursive
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: './dist/*'
    discard-paths: yes
